# https://toml.io/en/
name = "zinc"
version = "1.0.0"
dirs = [
    "cmd/zinc",          # dirs
    "cmd/zinc-balanced",
    "cmd/zinc-secured",
    "cmd/zinc-sshd",
    "cmd/zinc-sliced",
    "cli/netcat",
    "single/zincs",
]

[[files]]
path = "LICENSE"
destination = "share"
newname = "copyright.txt"
norename = true

[[files]]
path = "config/server.crt"
destination = "config"

[[files]]
path = "config/server.key"
destination = "config"

[[files]]
path = "config/zinc-balanced.toml"
destination = "config"

[[files]]
path = "config/zinc-secured.toml"
destination = "config"

[[files]]
path = "config/zinc-sshd.toml"
destination = "config"

[[files]]
path = "config/zinc-sliced.toml"
destination = "config"

[[files]]
path = "config/zinc.toml"
destination = "config"

[[files]]
path = "config/zincs.toml"
destination = "config"

[[files]]
path = "config/ssh/id_ed25519"
destination = "config/ssh"
