name = "zinc-sliced"
description = "zinc-sliced - Redesigned Git Backend GPRC Service"
destination = "bin"
version = "1.0.0"
versioninfo = "res/versioninfo.json"
manifest = "res/zinc-sliced.manifest"
goflags = [
    "-ldflags",
    "-X 'main.VERSION=$BUILD_VERSION' -X 'main.BUILDTIME=$BUILD_TIME' -X 'main.BUILDBRANCH=$BUILD_BRANCH' -X 'main.BUILDCOMMIT=$BUILD_COMMIT' -X 'main.GOVERSION=$BUILD_GOVERSION'",
]
