# zinc-secured config
Listen = "127.0.0.1:9418"
IdleTimeout = "120m"
MaxTiemout = "1h"
# Git over TLS
TlsListen = "127.0.0.1:9419"
# Git over QUIC
QuicListen = "127.0.0.1:9420"
Certificate = "${APPDIR}/config/server.crt"
CertificateKey = "${APPDIR}/config/server.key"
