# zinc-secured config
[core]
listen = "127.0.0.1:9418"

[tls]
listen = "127.0.0.1:9419"
certfile = "${APPDIR}/config/server.crt"
keyfile = "${APPDIR}/config/server.key"

[quic]
listen = "127.0.0.1:9420"
certfile = "${APPDIR}/config/server.crt"
keyfile = "${APPDIR}/config/server.key"
