name = "silver-httpd"
description = "silver-httpd - Redesigned Git Over HTTP Server"
destination = "bin"
version = "1.0.0"
versioninfo = "res/versioninfo.json"
manifest = "res/silver-httpd.manifest"
goflags = [
    "-ldflags",
    "-X 'main.VERSION=$BUILD_VERSION' -X 'main.BUILDTIME=$BUILD_TIME' -X 'main.BUILDBRANCH=$BUILD_BRANCH' -X 'main.BUILDCOMMIT=$BUILD_COMMIT' -X 'main.GOVERSION=$BUILD_GOVERSION'",
]
